### ISSUE TITLE
Make the Website Responsive

### ISSUE THREAD

**Issue by eshan1925** [eshan1925/EshanBlogs#1]
The pages of the website are not responsive yet so add responsivity to them.
You can also add some extra features if you want using javascript but responsivity is the main issue.

**Comment by riyaku11** [comment]
can i work on this issue?

**Comment by eshan1925** [comment]
> can i work on this issue?

Yeah sure @riyaku11

**Comment by eshan1925** [comment]
Yes start working on it and create a new pull request for the repo.
Please also let me know how much time will you take....
Thankyou

**Comment by riyaku11** [comment]
I will create the pull request by tomorrow.

**Comment by eshan1925** [comment]
Great, thanks!
